### ISSUE TITLE
Typos in map of ibmqx3

### ISSUE THREAD

**Issue by rraymondhp** [QISKit/ibmqx-backend-information#6]
The coupling map here overwrites the key `4`:
```
coupling_map = {1: [2], 2: [3], 4: [3], 4: [5], 6: [7], 8: [7], 9: [10], 11: [10], 12: [11], 12: [13], 13: [14], 15: [14], 15: [0], 0: [1], 3: [14], 13: [4], 12: [5], 6: [11], 7: [10], 9: [8]}
```

https://github.com/QISKit/ibmqx-backend-information/tree/master/backends/ibmqx3

Thanks to @itoko who pointed out this.

**Comment by rraymondhp** [comment]
I found that the same problem in mapping dictionary for the new `ibmqx5`: keys `3` and `6` are overwritten. 
```
coupling_map = {1:[2], 2:[3], 3:[4], 3:[14], 5:[4], 6:[7], 6:[11], 7:[10], 8:[7], 9:[8], 
9:[10],11:[10], 12:[5], 12:[11], 12:[13], 13:[4], 13:[14], 15:[0], 15:[2], 15:[14]}
```

https://github.com/QISKit/ibmqx-backend-information/tree/master/backends/ibmqx5

**Comment by mosandbe** [comment]
Updated the map so that all targets are in a list for each control key.

**Comment by rraymondhp** [comment]
Thanks for the quick response.
The coupling map of `ibmqx3` is still not fixed yet. 

https://github.com/QISKit/ibmqx-backend-information/tree/master/backends/ibmqx3
