### ISSUE TITLE
Coupling map inconsistency for ibmqx5

### ISSUE THREAD

**Issue by decodoku** [QISKit/ibmqx-backend-information#7]
The coupling map is not consistent with the image. I believe it should be

coupling_map = {1:[0,2], 2:[3], 3:[4, 14], 5:[4], 6:[5,7,11], 7:[10], 8:[7],9:[8, 10], 11:[10], 12:[5, 11, 13], 13:[4, 14], 15:[0, 2, 14]}

**Comment by ajavadia** [comment]
Thanks for pointing this out. You are right. The current Github documentation has a few mistakes. Yours is correct and consistent with the Quantum Experience website. I will fix this.

**Comment by jaygambetta** [comment]
closing after @ajavadia fix
